app/admin/__init__.py
from flask import Blueprint


bp = Blueprint('admin',
               __name__,
               template_folder="templates",
               static_folder="static",
               )

from app.admin.routes import *

app/admin/routes.py
# Marketing\app\admin\routes.py

from app.admin import bp
from app.utils import admin_required
from app.database import db
from app.models import Agency, Customer, LexAcc
from flask import render_template, redirect, session, url_for, request

@bp.get("/")
@admin_required
def main():
    if not session.get("currentAgency").get("isAdmin"):
        return redirect(url_for("main.lex_main"))
    return render_template("main.html")

@bp.route("/all-agency")
@admin_required
def all_agency():
    source = request.args.get("source")
    result = db.session.execute(
            db.select(Agency, LexAcc).join(LexAcc).where(
               LexAcc.source == source
               ).order_by(Agency.id.desc())
            ).all()
    return render_template("htmx/all_agency.html", result=result)

@bp.route('/get-customer/<int:lexid>')
@admin_required
def get_customer(lexid: int):
    currentLexacc = db.get_or_404(LexAcc, lexid)
    customers = db.session.execute(
            db.select(Customer).filter_by(lexAccId=currentLexacc.id)
            ).scalars().fetchall()
    return render_template(
            "get_customer.html",
            customers=customers
            )

app/admin/templates/get_customer.html
<!--Marketing\app\admin\templates\get_customer.html -->

{% extends "base.html" %}
{% block head %}
	<title>Admin View| Marketing Agency</title>
{% endblock %}
{% block body %}
<div class="container">
	<section class="my-3">
		<h1 class="display-1">Admin View</h1>
		<p class="lead">List of all the customers linked to this lex Office/Sevdesk account.<p>
		<div class="mt-5 row">
			<div class="col-2 mr-auto">
				<a class="btn btn-outline-info" href="{{ url_for('admin.main') }}">Back</a>
			</div>
			<div class="col-4 mx-auto">
				<p class="text-start"> total gross amount: 
				{% set ns = namespace(totalGross=0.0, totalNet=0.0) %}
				{% for c in customers %}
				{% set ns.totalGross = ns.totalGross+c.totalGrossAmount %}
				{% set ns.totalNet = ns.totalNet+c.totalNetAmount %}
				{% endfor %}
				<span class="text-end p-1 text-bg-success">{{ ns.totalGross }}</span>
				</p>
			</div>
			<div class="col-4 ms-auto">
				<p class="text-start"> total net amount: 
				<span class="text-end p-1 text-bg-success">{{ ns.totalNet }}</span>
				</p>
			</div>
		</div>
	</section>
	<section>
		<table class="table table-bordered table-striped table-hover">
			<thead>
				<tr>
					<th scope="col">S.no.</th>
					<th scope="col">Customer Name</th>
					<th scope="col" class="text-center">Gross Amounts</th>
					<th scope="col" class="text-center">Net Amounts</th>
				</tr>
			</thead>
			<tbody>
				{% for customer in customers %}
				<tr>
					<th scope="row">{{ loop.index }}</th>
					<td>{{ customer.name }}</td>
					<td class="text-center">
						<p class="text-success">{{ customer.totalGrossAmount }}</p>
					</td>
					<td class="text-center">
						<p class="text-success">{{ customer.totalNetAmount }}</p>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</section>
</div>
{% endblock %}


app/admin/templates/htmx/all_agency.html
<!--app\admin\templates\htmx\all_agency.html -->
<div class="accordion" id="accordionPanelsStayOpenExample">
	{% for r in result %}
	{% if loop.changed(r.Agency.id) %}
	<div class="accordion-item">
		<h2 class="accordion-header">
			<button class="accordion-button {% if not loop.first %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-{{ loop.index }}" {% if loop.first %}aria-expanded="true"{% endif %} aria-controls="panelsStayOpen-{{ loop.index }}">
				{{ r.Agency.email }}
			</button>
		</h2>
		<div id="panelsStayOpen-{{ loop.index }}" class="accordion-collapse collapse {% if loop.first %}show{% endif %}">
			<div class="accordion-body">
				<table class="table table-striped table-bordered">
					<thead>
						<tr>
							<th scope="col">#</th>
							<th scope="col">Client name</th>
							<th scope="col">Customers</th>
							<th scope="col">Added on. (UTC Time)</th>
						</tr>
					</thead>
					<tbody>
	{% endif %}
						<tr>
							<td scope="row">{{ loop.index }}</td>
							<td>{{ r.LexAcc.name }}</td>
							<td><a href="{{ url_for('admin.get_customer', lexid=r.LexAcc.id) }}">List of customers</a></td>
							<td>{{ r.LexAcc.added_on.strftime("%d-%b-%Y") }}</td>
						</tr>
	{% if loop.nextitem is defined and loop.nextitem.Agency.id != r.Agency.id %}
				</tbody>
			</table>
			</div>
		</div>
	</div>
	{% endif %}
	{% endfor %}
</div>

app/admin/templates/main.html
<!-- app\admin\templates\main.html -->
{% extends "base.html" %}
{% block head %}
	<title>admin view | track leads.</title>
{% endblock %}
{% block body %}
<div class="container">
	<section class="my-3">
		<h1 class="display-1">Admin view of marketing agency</h1>
		<p class="lead">In this page you'll get the list of all the marketing agency and lexoffice/sevdesk account linked to them with total income made.<p>
		<p class="lead">Click on below button to switch between list of lex office accounts and list of sevdesk accounts<p>
		<div class="mt-5 form-check form-check-inline">
			<input type="radio" class="btn-check" name="options-outlined" id="lexoffice-btn" autocomplete="off" checked hx-get="{{ url_for('admin.all_agency') }}" hx-trigger="load,change" hx-target="#agency-return" hx-indicator="#indicator" hx-vals='{"source":"Lex"}'>
			<label class="btn btn-lg btn-outline-success px-4" for="lexoffice-btn">Lex Office</label>
			<input type="radio" class="btn-check" name="options-outlined" id="sevdesk-btn" autocomplete="off" hx-get="{{ url_for('admin.all_agency') }}" hx-target="#agency-return" hx-indicator="#indicator" hx-vals='{"source":"Sev"}'>
			<label class="btn btn-lg btn-outline-success ms-4 px-4" for="sevdesk-btn">Sevdesk</label>
		<div id="indicator" class="d-inline htmx-indicator text-center m-5">
			<div class="spinner-grow text-success" role="status">
				<span class="visually-hidden">Loading...</span>
			</div>
		</div>
		</div>
	</section>
		<section id="agency-return">
		</section>
</div>
{% endblock %}